version: 2.1

orbs:
  python: circleci/python@2.0.1
  docker: circleci/docker@2.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  lint-and-test:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linting
          command: flake8
      - run:
          name: Run testing
          command: pytest --reuse-db --no-migrations
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: ${DOCKER_LOGIN}/oc_lettings
      - docker/push:
          image: ${DOCKER_LOGIN}/oc_lettings
  heroku-deploy:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  deploy-application:
    jobs:
      - lint-and-test
      - build-and-push:
          requires:
            - lint-and-test
          filters:
            branches:
              only: master
      - heroku-deploy:
          pre-steps:
            - run:
                command: heroku config:set SECRET_KEY=$SECRET_KEY -a oclettings22
            _ run:
                command: heroku config:set DSN=$DSN -a oclettings22
          requires:
            - build-and-push
          filters:
            branches:
              only: master
